version: '3.4'
#@see https://docs.docker.com/compose/compose-file/compose-file-v3/
x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-file: "5"
    max-size: "20m"

services:
  nginx:
    build: ./docker/nginx/build
    image: nginx
    container_name: ${APP_NAME}_app_nginx
    restart: unless-stopped
    depends_on:
      - php
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker/nginx/config:/etc/nginx/conf.d:ro
      - ./app:/app
    logging: *default-logging

  db:
    image: mariadb
    container_name: ${APP_NAME}_app_db
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./db/data:/var/lib/mysql
    logging: *default-logging

  php:
    build:
      context: ./docker/php/build
      dockerfile: Dockerfile
    container_name: ${APP_NAME}_app_php
    restart: unless-stopped
    depends_on:
      - db
    volumes:
      - composer:/root/.composer/cache
      - ./app:/app
    logging: *default-logging

  rabbitmq:
    build: ./docker/rabbitmq
    restart: always
    container_name: ${APP_NAME}_app_rabbitmq
    image: rabbitmq:management
    hostname: rabbitmq
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq:cached
    logging: *default-logging

volumes:
  composer: